version: '1'

services:
  container-watcher:
    container_name: container-watcher
    image: ghcr.io/sphexi/container-watcher:main
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock